name: Check GraphQL
description: Checks your GraphQL endpoint for problems
author: 'Dylan Anthony'
branding:
  icon: check-circle
  color: purple
inputs:
  endpoint:
    description: 'The GraphQL endpoint to check'
    required: true
  auth:
    description: 'The Authorization header to use'
    required: false
    default: ''
  subgraph:
    description: 'Whether the graph is a subgraph'
    required: false
    default: 'false'
  allow_introspection:
    description: 'Whether introspection is allowed, defaults to value of `subgraph`'
    required: false
    default: ''
  insecure_subgraph:
    description: 'Whether the subgraph is allowed to be insecure'
    required: false
    default: 'false'
outputs:
  error:
    description: 'The description of any error that occurred'
runs:
  using: 'docker'
  image: 'ghcr.io/dbanty/graphql-check-action:experimental'
  args:
    - ${{ inputs.endpoint }}
    - ${{ inputs.auth }}
    - ${{ inputs.subgraph }}
    - ${{ inputs.allow_introspection }}
    - ${{ inputs.insecure_subgraph }}
