name: Unit tests, linting, and formatting
on: [push]
jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Switch to Nightly
        run: |
          rustup override set nightly
          rustup update nightly
          rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt --check
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Update Rust
        run: |
          rustup override set stable
          rustup update stable
      - name: Run tests
        run: cargo test
        env:
          GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}
      - name: Lint
        run: cargo clippy